const getRandomWord = () => {
  const words = [
    // Easy - animals
    "cat",
    "dog",
    "fish",
    "bird",
    "duck",
    "frog",
    "bear",
    "lion",
    "cow",
    "pig",
    "sheep",
    "horse",
    "rabbit",
    "snake",
    "owl",
    "bat",
    "crab",
    "snail",
    "bee",
    "ant",
    "butterfly",
    "turtle",
    "whale",
    "shark",
    "fox",
    "deer",
    "wolf",
    "monkey",
    "elephant",
    "penguin",
    "giraffe",
    "zebra",
    "crocodile",
    "parrot",
    "flamingo",
    "gorilla",
    "panda",
    "koala",
    "camel",
    "kangaroo",
    "rhino",
    "hippo",
    "cheetah",
    "leopard",
    "jaguar",
    "tiger",
    "polar bear",
    "grizzly bear",
    "hamster",
    "hedgehog",
    "squirrel",
    "beaver",
    "otter",
    "seal",
    "walrus",
    "dolphin",
    "octopus",
    "jellyfish",
    "lobster",
    "seahorse",
    "starfish",
    "clam",
    "shrimp",
    "catfish",
    "swordfish",
    "pufferfish",
    "eagle",
    "hawk",
    "peacock",
    "toucan",
    "pelican",
    "stork",
    "robin",
    "sparrow",
    "crow",
    "pigeon",
    "hummingbird",
    "ostrich",
    "emu",
    "swan",
    "rooster",
    "chick",
    "turkey",
    "goose",
    "dragonfly",
    "ladybug",
    "cricket",
    "grasshopper",
    "caterpillar",
    "worm",
    "spider",
    "scorpion",
    "lizard",
    "chameleon",
    "iguana",
    "gecko",
    "salamander",
    "toad",
    "newt",
    "python",
    "cobra",
    "rattlesnake",
    "alligator",
    "tortoise",
    "narwhal",
    "platypus",
    "armadillo",
    "sloth",
    "anteater",
    "meerkat",
    "warthog",
    "baboon",
    "lemur",

    // Easy - food & drink
    "apple",
    "cake",
    "pizza",
    "bread",
    "egg",
    "banana",
    "carrot",
    "cookie",
    "ice cream",
    "donut",
    "burger",
    "hotdog",
    "taco",
    "grape",
    "lemon",
    "mushroom",
    "strawberry",
    "watermelon",
    "popcorn",
    "coffee",
    "orange",
    "pear",
    "peach",
    "mango",
    "pineapple",
    "cherry",
    "blueberry",
    "raspberry",
    "avocado",
    "tomato",
    "potato",
    "corn",
    "broccoli",
    "cucumber",
    "onion",
    "garlic",
    "pepper",
    "spinach",
    "lettuce",
    "pumpkin",
    "coconut",
    "kiwi",
    "melon",
    "fig",
    "plum",
    "pomegranate",
    "lychee",
    "papaya",
    "guava",
    "sandwich",
    "soup",
    "salad",
    "pasta",
    "noodles",
    "rice",
    "steak",
    "chicken",
    "fish and chips",
    "fried egg",
    "pancake",
    "toast",
    "cereal",
    "yogurt",
    "cheese",
    "butter",
    "jam",
    "honey",
    "syrup",
    "chocolate",
    "candy",
    "lollipop",
    "cupcake",
    "muffin",
    "brownie",
    "pie",
    "tart",
    "cheesecake",
    "pudding",
    "jelly",
    "milkshake",
    "juice",
    "tea",
    "milk",
    "soda",
    "smoothie",
    "lemonade",
    "hot chocolate",
    "boba tea",

    // Easy - everyday objects
    "hat",
    "book",
    "cup",
    "ball",
    "star",
    "key",
    "shoe",
    "sock",
    "bag",
    "box",
    "bell",
    "drum",
    "chair",
    "table",
    "door",
    "window",
    "bed",
    "clock",
    "phone",
    "flag",
    "ring",
    "bow",
    "candle",
    "glasses",
    "brush",
    "pencil",
    "pen",
    "eraser",
    "ruler",
    "scissors",
    "stapler",
    "notebook",
    "envelope",
    "stamp",
    "coin",
    "wallet",
    "purse",
    "umbrella",
    "glove",
    "scarf",
    "belt",
    "tie",
    "button",
    "zipper",
    "needle",
    "thread",
    "pin",
    "mirror",
    "comb",
    "toothbrush",
    "toothpaste",
    "soap",
    "shampoo",
    "razor",
    "towel",
    "pillow",
    "blanket",
    "lamp",
    "fan",
    "remote control",
    "battery",
    "bulb",
    "plug",
    "switch",
    "nail",
    "screw",
    "hammer",
    "wrench",
    "saw",
    "drill",
    "tape",
    "glue",
    "bucket",
    "mop",
    "broom",
    "dustpan",
    "trash can",
    "bowl",
    "plate",
    "fork",
    "spoon",
    "knife",
    "mug",
    "bottle",
    "jar",
    "pan",
    "pot",
    "kettle",
    "microwave",
    "toaster",
    "blender",
    "fridge",
    "oven",
    "calculator",
    "keyboard",
    "mouse",
    "headphones",
    "speaker",
    "camera",
    "watch",
    "bracelet",
    "necklace",
    "earring",
    "crown",
    "trophy",
    "medal",

    // Easy - nature & weather
    "sun",
    "moon",
    "cloud",
    "rain",
    "snow",
    "tree",
    "flower",
    "leaf",
    "mountain",
    "river",
    "fire",
    "wave",
    "rainbow",
    "rock",
    "grass",
    "lightning",
    "wind",
    "fog",
    "hail",
    "storm",
    "sunset",
    "sunrise",
    "tornado",
    "snowflake",
    "icicle",
    "puddle",
    "mud",
    "sand",
    "dirt",
    "pebble",
    "boulder",
    "cliff",
    "valley",
    "hill",
    "plain",
    "forest",
    "jungle",
    "desert",
    "swamp",
    "marsh",
    "pond",
    "lake",
    "ocean",
    "sea",
    "beach",
    "shore",
    "cave",
    "waterfall",
    "geyser",
    "volcano",
    "glacier",
    "iceberg",
    "coral reef",
    "island",
    "peninsula",
    "bay",
    "tide",
    "current",
    "rose",
    "daisy",
    "tulip",
    "sunflower",
    "lily",
    "orchid",
    "daffodil",
    "oak tree",
    "palm tree",
    "pine tree",
    "cactus",
    "bamboo",
    "seaweed",
    "mushroom",
    "fern",
    "moss",
    "vine",
    "thorn",
    "seed",
    "acorn",
    "pinecone",

    // Easy - places & buildings
    "house",
    "school",
    "hospital",
    "church",
    "castle",
    "tower",
    "bridge",
    "farm",
    "barn",
    "stable",
    "garage",
    "factory",
    "store",
    "market",
    "restaurant",
    "cafe",
    "bakery",
    "library",
    "museum",
    "cinema",
    "theater",
    "stadium",
    "gym",
    "pool",
    "park",
    "playground",
    "zoo",
    "circus",
    "airport",
    "train station",
    "bus stop",
    "harbor",
    "dock",
    "lighthouse",
    "igloo",
    "tent",
    "cabin",
    "mansion",
    "skyscraper",
    "windmill",
    "pyramid",

    // Easy - vehicles & transport
    "car",
    "bus",
    "train",
    "plane",
    "boat",
    "bicycle",
    "motorcycle",
    "truck",
    "van",
    "taxi",
    "ambulance",
    "fire truck",
    "police car",
    "helicopter",
    "submarine",
    "ship",
    "canoe",
    "kayak",
    "sailboat",
    "hot air balloon",
    "rocket",
    "spaceship",
    "tractor",
    "bulldozer",
    "crane",
    "forklift",
    "scooter",
    "skateboard",
    "roller skates",
    "sled",
    "sleigh",
    "chariot",
    "rickshaw",
    "gondola",
    "ferry",
    "blimp",

    // Medium - objects & tools
    "telescope",
    "microscope",
    "compass",
    "anchor",
    "shield",
    "sword",
    "bow and arrow",
    "crossbow",
    "catapult",
    "cannon",
    "spear",
    "axe",
    "dagger",
    "whip",
    "net",
    "trap",
    "cage",
    "chain",
    "lock",
    "padlock",
    "safe",
    "vault",
    "chest",
    "drawer",
    "shelf",
    "cabinet",
    "wardrobe",
    "bookcase",
    "closet",
    "attic",
    "basement",
    "balcony",
    "chimney",
    "fireplace",
    "furnace",
    "radiator",
    "air conditioner",
    "water heater",
    "solar panel",
    "windmill",
    "water wheel",
    "pulley",
    "lever",
    "gear",
    "spring",
    "magnet",
    "battery",
    "circuit",
    "wire",
    "antenna",
    "satellite",
    "periscope",
    "binoculars",
    "magnifying glass",
    "sundial",
    "hourglass",
    "thermometer",
    "barometer",
    "weather vane",
    "scale",
    "measuring tape",
    "syringe",
    "stethoscope",
    "scalpel",
    "bandage",
    "cast",
    "crutch",
    "wheelchair",
    "stretcher",
    "oxygen mask",

    // Medium - clothing & accessories
    "dress",
    "suit",
    "jacket",
    "coat",
    "raincoat",
    "hoodie",
    "sweater",
    "shirt",
    "t-shirt",
    "blouse",
    "skirt",
    "shorts",
    "jeans",
    "trousers",
    "pajamas",
    "swimsuit",
    "wetsuit",
    "uniform",
    "apron",
    "cape",
    "cloak",
    "robe",
    "toga",
    "kimono",
    "sari",
    "turban",
    "beret",
    "helmet",
    "crown",
    "tiara",
    "veil",
    "mask",
    "goggles",
    "snorkel",
    "backpack",
    "suitcase",
    "briefcase",
    "handbag",
    "tote bag",
    "fanny pack",
    "lanyard",
    "badge",

    // Medium - sports & activities
    "swimming",
    "dancing",
    "cooking",
    "sleeping",
    "fishing",
    "climbing",
    "painting",
    "reading",
    "running",
    "flying",
    "surfing",
    "camping",
    "skydiving",
    "gardening",
    "bowling",
    "archery",
    "juggling",
    "diving",
    "skiing",
    "snowboarding",
    "skateboarding",
    "rollerblading",
    "cycling",
    "rowing",
    "sailing",
    "kayaking",
    "hiking",
    "rock climbing",
    "bungee jumping",
    "paragliding",
    "hang gliding",
    "zip lining",
    "rafting",
    "scuba diving",
    "snorkeling",
    "cliff diving",
    "ice skating",
    "hockey",
    "football",
    "basketball",
    "baseball",
    "tennis",
    "badminton",
    "volleyball",
    "cricket",
    "rugby",
    "golf",
    "polo",
    "fencing",
    "boxing",
    "wrestling",
    "karate",
    "judo",
    "gymnastics",
    "ballet",
    "yoga",
    "meditation",
    "weightlifting",
    "pole vault",
    "long jump",
    "high jump",
    "hurdles",
    "relay race",
    "marathon",
    "triathlon",
    "decathlon",
    "tug of war",
    "arm wrestling",

    // Medium - music & arts
    "guitar",
    "piano",
    "violin",
    "cello",
    "trumpet",
    "trombone",
    "saxophone",
    "flute",
    "clarinet",
    "oboe",
    "harp",
    "banjo",
    "ukulele",
    "mandolin",
    "accordion",
    "harmonica",
    "bagpipe",
    "xylophone",
    "marimba",
    "vibraphone",
    "drums",
    "bongo",
    "tambourine",
    "triangle",
    "cymbals",
    "maracas",
    "microphone",
    "speaker",
    "headphones",
    "record",
    "cassette",
    "CD",
    "conductor",
    "orchestra",
    "choir",
    "opera",
    "concert",
    "stage",
    "spotlight",
    "curtain",
    "puppet",
    "marionette",
    "mime",
    "clown",
    "acrobat",
    "trapeze",
    "tightrope",
    "magic wand",
    "top hat",

    // Medium - fantasy & mythology
    "dragon",
    "unicorn",
    "phoenix",
    "griffin",
    "centaur",
    "minotaur",
    "mermaid",
    "siren",
    "kraken",
    "hydra",
    "manticore",
    "chimera",
    "fairy",
    "elf",
    "dwarf",
    "gnome",
    "goblin",
    "troll",
    "ogre",
    "vampire",
    "werewolf",
    "zombie",
    "ghost",
    "witch",
    "wizard",
    "sorcerer",
    "warlock",
    "necromancer",
    "paladin",
    "ranger",
    "rogue",
    "knight",
    "pirate",
    "ninja",
    "samurai",
    "gladiator",
    "viking",
    "pharaoh",
    "gladiator",
    "spartan",
    "jester",
    "bard",
    "monk",

    // Medium - space & science
    "planet",
    "asteroid",
    "comet",
    "meteor",
    "nebula",
    "galaxy",
    "star",
    "black hole",
    "wormhole",
    "astronaut",
    "cosmonaut",
    "space station",
    "satellite",
    "telescope",
    "observatory",
    "crater",
    "solar system",
    "orbit",
    "eclipse",
    "aurora",
    "supernova",
    "atom",
    "molecule",
    "DNA",
    "cell",
    "bacteria",
    "virus",
    "test tube",
    "beaker",
    "flask",
    "bunsen burner",
    "petri dish",
    "robot",
    "android",
    "cyborg",
    "drone",
    "laser",
    "hologram",

    // Hard - complex scenes & concepts
    "avalanche",
    "tsunami",
    "earthquake",
    "hurricane",
    "blizzard",
    "drought",
    "flood",
    "wildfire",
    "eruption",
    "landslide",
    "quicksand",
    "labyrinth",
    "maze",
    "wormhole",
    "time machine",
    "teleportation",
    "time travel",
    "invisibility",
    "levitation",
    "shadow",
    "reflection",
    "echo",
    "mirage",
    "illusion",
    "camouflage",
    "metamorphosis",
    "hibernation",
    "migration",
    "evolution",
    "extinction",
    "fossil",
    "archaeological dig",
    "gravity",
    "weightlessness",
    "zero gravity",
    "black hole",
    "wrecking ball",
    "demolition",
    "construction",
    "excavation",
    "deforestation",
    "pollution",
    "recycling",
    "composting",
    "solar eclipse",
    "lunar eclipse",
    "blood moon",
    "supermoon",
    "northern lights",
    "bioluminescence",
    "photosynthesis",
    "symbiosis",
    "parasitism",
    "food chain",
    "ecosystem",
    "tectonic plates",
    "continental drift",
    "ice age",

    // Hard - complex objects
    "kaleidoscope",
    "boomerang",
    "drawbridge",
    "catapult",
    "trebuchet",
    "aqueduct",
    "colosseum",
    "amphitheater",
    "acropolis",
    "ziggurat",
    "pagoda",
    "minaret",
    "cathedral",
    "basilica",
    "mausoleum",
    "hot air balloon",
    "airship",
    "zeppelin",
    "hovercraft",
    "conveyor belt",
    "escalator",
    "treadmill",
    "assembly line",
    "printing press",
    "typewriter",
    "telegraph",
    "phonograph",
    "periscope",
    "sextant",
    "astrolabe",
    "orrery",
    "diving bell",
    "bathysphere",
    "submersible",
    "glider",
    "biplane",
    "fighter jet",
    "stealth bomber",
    "aircraft carrier",
    "battleship",
    "galleon",
    "trireme",

    // Hard - professions & characters
    "archaeologist",
    "astronomer",
    "cartographer",
    "cryptographer",
    "entomologist",
    "geologist",
    "meteorologist",
    "oceanographer",
    "paleontologist",
    "volcanologist",
    "epidemiologist",
    "acupuncturist",
    "anesthesiologist",
    "cardiologist",
    "neurologist",
    "orthodontist",
    "orthopedist",
    "pediatrician",
    "psychiatrist",
    "radiologist",
    "surgeon",
    "veterinarian",
    "architect",
    "blacksmith",
    "beekeeper",
    "candlemaker",
    "clockmaker",
    "glassblower",
    "jeweler",
    "locksmith",
    "lumberjack",
    "miller",
    "potter",
    "sculptor",
    "taxidermist",
    "tightrope walker",
    "ventriloquist",
    "puppeteer",
    "stunt double",
    "sommelier",
    "patissier",
    "sushi chef",
    "mixologist",

    // Hard - abstract visual concepts
    "perspective",
    "symmetry",
    "optical illusion",
    "paradox",
    "infinity",
    "dimension",
    "frequency",
    "vibration",
    "resonance",
    "electricity",
    "magnetism",
    "radioactivity",
    "antimatter",
    "quantum",
    "relativity",
    "thermodynamics",
    "entropy",
    "democracy",
    "monarchy",
    "anarchy",
    "utopia",
    "dystopia",
    "nostalgia",
    "deja vu",
    "existentialism",
    "nihilism",
  ];

  return words[Math.floor(Math.random() * words.length)];
};

module.exports = getRandomWord;
